using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;

namespace xlwrite;

/// <summary>
/// Writes a <see cref="FormatScript"/> as a VBA module: a public 'XlWriteFormat' Sub followed by private helpers.
/// Table bounds and filters are resolved when the macro runs; 'cond' rules become live conditional formats.
/// </summary>
public class VbaFormatWriter
{
    public const string MacroName = "XlWriteFormat";

    private readonly StringBuilder _b = new();

    public static string Write(FormatScript script) => new VbaFormatWriter().WriteScript(script);

    private string WriteScript(FormatScript script)
    {
        Line(0, "' Generated by xlwrite. Run XlWriteFormat to apply the formatting.");
        Line(0, $"Public Sub {MacroName}()");
        Line(1, "Dim ws As Worksheet");
        Line(1, "Dim rng As Range, tl As Range, a As Range, c As Range");
        Line(1, "Dim kept As Range, rs As Range, re As Range");
        Line(1, "Dim v As Variant, x1 As Variant, x2 As Variant");
        Line(1, "Dim f1 As String, f2 As String");
        Line(1, "Dim counts As Collection");
        Line(1, "Dim fc As Object");
        Line(0, "");
        Line(1, "Application.ScreenUpdating = False");

        foreach (FormatItem item in script.Items)
        {
            // Selections on different sheets can't be unioned, so each sheet gets its own block.
            foreach (IGrouping<string?, Selection> group in item.Selections.GroupBy(s => s.Sheet))
            {
                WriteGroup(item, group.Key, group.ToList());
            }
        }

        Line(0, "");
        Line(1, "Application.ScreenUpdating = True");
        Line(0, "End Sub");
        // The source file is checked out with CRLF endings, which would otherwise leak into the raw string.
        _b.Append(Helpers.Replace("\r\n", "\n"));
        return _b.ToString();
    }

    private void WriteGroup(FormatItem item, string? sheet, List<Selection> selections)
    {
        Line(0, "");
        Line(1, $"' Line {item.Line}");
        Line(1, sheet is null ? "Set ws = ActiveSheet" : $"Set ws = ActiveWorkbook.Worksheets({Str(sheet)})");
        Line(1, "Set rng = Nothing");
        foreach (Selection selection in selections)
        {
            Line(1, $"Set rng = XlwUnion(rng, {SelectionExpression(selection)})");
        }
        // Relative references in filters and conditional formulas are relative to this cell.
        Line(1, "If Not rng Is Nothing Then Set tl = rng.Areas(1).Cells(1, 1)");

        if (item.Filters.Any())
        {
            // Whole column and row selections would otherwise loop over millions of cells.
            Line(1, "If Not rng Is Nothing Then Set rng = Application.Intersect(rng, ws.UsedRange)");
            foreach (Condition filter in item.Filters) WriteFilter(filter);
        }

        Line(1, "If Not rng Is Nothing Then");
        foreach (FormatElement element in item.Elements)
        {
            switch (element)
            {
                case FormatAction action:
                    WriteStaticAction(action);
                    break;
                case CfRule rule:
                    WriteCfRule(rule);
                    break;
            }
        }
        Line(1, "End If");
    }

    private static string SelectionExpression(Selection s)
    {
        if (s.Kind != RefKind.Table) return $"ws.Range({Str(s.Address)})";

        string table = $"XlwTable(ws.Range({Str(s.Address)}))";
        return s.Part switch
        {
            TablePart.All => table,
            TablePart.Header => $"XlwTablePart({table}, \"header\")",
            TablePart.Body => $"XlwTablePart({table}, \"body\")",
            TablePart.LastRow => $"XlwTablePart({table}, \"lastrow\")",
            TablePart.Column => $"XlwTableColumn({table}, {Str(s.ColumnName!)})",
            _ => throw new InvalidOperationException(),
        };
    }

    // Filters

    private void WriteFilter(Condition condition)
    {
        Line(1, "If Not rng Is Nothing Then");
        string predicate = FilterPredicate(condition);
        Line(2, "Set kept = Nothing: Set rs = Nothing: Set re = Nothing");
        Line(2, "For Each a In rng.Areas");
        Line(3, "For Each c In a.Cells");
        Line(4, "v = c.Value");
        Line(4, $"If {predicate} Then XlwKeep kept, rs, re, c");
        Line(3, "Next c");
        Line(2, "Next a");
        Line(2, "XlwKeep kept, rs, re, Nothing");
        Line(2, "Set rng = kept");
        Line(1, "End If");
    }

    /// <summary>
    /// Writes any setup the condition needs and returns a VBA boolean expression over the cell value 'v'.
    /// </summary>
    private string FilterPredicate(Condition condition)
    {
        switch (condition)
        {
            case CompareCondition cmp:
                return $"XlwCompare(v, {Str(VbaCompareOp(cmp.Op))}, {FilterOperand(cmp.Value, "x1", "f1")})";
            case BetweenCondition between:
            {
                string low = FilterOperand(between.Low, "x1", "f1");
                string high = FilterOperand(between.High, "x2", "f2");
                return $"XlwBetween(v, {low}, {high}, {Bool(between.Negate)})";
            }
            case TextCondition text:
                string op = text.Op switch
                {
                    TextOp.Contains => "contains",
                    TextOp.NotContains => "notcontains",
                    TextOp.BeginsWith => "begins",
                    _ => "ends",
                };
                return $"XlwText(v, {Str(op)}, {Str(text.Text)})";
            case CellStateCondition state:
                return state.State switch
                {
                    CellState.Blank => "XlwBlank(v)",
                    CellState.NonBlank => "Not XlwBlank(v)",
                    CellState.Error => "IsError(v)",
                    _ => "Not IsError(v)",
                };
            case RankCondition rank:
                Line(2, $"x1 = XlwRankThreshold(rng, {Bool(rank.Top)}, {rank.Rank}, {Bool(rank.Percent)})");
                return $"XlwCompare(v, {(rank.Top ? "\">=\"" : "\"<=\"")}, x1)";
            case AverageCondition avg:
                Line(2, "x1 = XlwAverage(rng)");
                return $"XlwCompare(v, {(avg.Above ? "\">\"" : "\"<\"")}, x1)";
            case DuplicateCondition dup:
                Line(2, "Set counts = XlwCounts(rng)");
                return $"XlwDupMatch(counts, v, {Bool(dup.Duplicate)})";
            case DatePeriodCondition date:
                return $"XlwDatePeriod(v, {Str(date.Period.ToString().ToLowerInvariant())})";
            case FormulaCondition formula:
                Line(2, $"f1 = XlwToR1C1({Str(formula.Formula)}, tl)");
                return "XlwTruthy(XlwEvalAt(f1, c))";
            default:
                throw new InvalidOperationException();
        }
    }

    /// <summary>
    /// Constants are inlined. Cell references are evaluated per cell so relative references shift like they do in Excel.
    /// </summary>
    private string FilterOperand(Operand operand, string valueVar, string formulaVar)
    {
        switch (operand)
        {
            case NumberOperand n: return Num(n.Value);
            case TextOperand t: return Str(t.Value);
            case CellOperand cell:
                Line(2, $"{formulaVar} = XlwToR1C1({Str("=" + cell.Address)}, tl)");
                return $"XlwEvalAt({formulaVar}, c)";
            default: throw new InvalidOperationException();
        }
    }

    private static string VbaCompareOp(CompareOp op) => op switch
    {
        CompareOp.Equal => "=",
        CompareOp.NotEqual => "<>",
        CompareOp.Less => "<",
        CompareOp.LessEqual => "<=",
        CompareOp.Greater => ">",
        _ => ">=",
    };

    // Static formatting

    private void WriteStaticAction(FormatAction action)
    {
        switch (action)
        {
            case ToggleAction t:
                Line(2, t.Property switch
                {
                    ToggleProperty.Bold => $"rng.Font.Bold = {Bool(t.On)}",
                    ToggleProperty.Italic => $"rng.Font.Italic = {Bool(t.On)}",
                    ToggleProperty.Underline => $"rng.Font.Underline = {(t.On ? "xlUnderlineStyleSingle" : "xlUnderlineStyleNone")}",
                    ToggleProperty.Strike => $"rng.Font.Strikethrough = {Bool(t.On)}",
                    _ => $"rng.WrapText = {Bool(t.On)}",
                });
                break;
            case FillAction f: Line(2, $"rng.Interior.Color = {Rgb(f.Color)}"); break;
            case FontColorAction f: Line(2, $"rng.Font.Color = {Rgb(f.Color)}"); break;
            case FontNameAction f: Line(2, $"rng.Font.Name = {Str(f.Name)}"); break;
            case FontSizeAction f: Line(2, $"rng.Font.Size = {Num(f.Size)}"); break;
            case WidthAction w: Line(2, $"rng.EntireColumn.ColumnWidth = {Num(w.Width)}"); break;
            case HeightAction h: Line(2, $"rng.EntireRow.RowHeight = {Num(h.Height)}"); break;
            case NumberFormatAction n: Line(2, $"rng.NumberFormat = {Str(n.Format)}"); break;
            case HAlignAction h:
                Line(2, $"rng.HorizontalAlignment = {h.Align switch { HAlign.Left => "xlLeft", HAlign.Center => "xlCenter", _ => "xlRight" }}");
                break;
            case VAlignAction v:
                Line(2, $"rng.VerticalAlignment = {v.Align switch { VAlign.Top => "xlTop", VAlign.Middle => "xlCenter", _ => "xlBottom" }}");
                break;
            case BorderAction border:
                (string lineStyle, string weight) = BorderLine(border.Style);
                foreach ((BorderSides side, string index) in StaticBorderIndexes)
                {
                    if ((border.Sides & side) == 0) continue;
                    Line(2, $"XlwBorder rng, {index}, {lineStyle}, {weight}, {Rgb(border.Color)}");
                }
                break;
            default:
                throw new InvalidOperationException();
        }
    }

    private static readonly (BorderSides, string)[] StaticBorderIndexes =
    {
        (BorderSides.Top, "xlEdgeTop"),
        (BorderSides.Bottom, "xlEdgeBottom"),
        (BorderSides.Left, "xlEdgeLeft"),
        (BorderSides.Right, "xlEdgeRight"),
        (BorderSides.InsideHorizontal, "xlInsideHorizontal"),
        (BorderSides.InsideVertical, "xlInsideVertical"),
    };

    private static (string LineStyle, string Weight) BorderLine(BorderStyle style) => style switch
    {
        BorderStyle.Thin => ("xlContinuous", "xlThin"),
        BorderStyle.Medium => ("xlContinuous", "xlMedium"),
        BorderStyle.Thick => ("xlContinuous", "xlThick"),
        BorderStyle.Dashed => ("xlDash", "xlThin"),
        BorderStyle.Dotted => ("xlDot", "xlThin"),
        BorderStyle.Double => ("xlDouble", "xlThick"),
        _ => ("xlLineStyleNone", "xlThin"),
    };

    // Conditional formatting

    private void WriteCfRule(CfRule rule)
    {
        switch (rule)
        {
            case ConditionalRule cond:
                WriteCfAdd(cond.Condition);
                foreach (FormatAction action in cond.Actions) WriteCfAction(action);
                if (cond.Stop) Line(2, "fc.StopIfTrue = True");
                break;
            case ColorScaleRule scale:
                Line(2, $"Set fc = rng.FormatConditions.AddColorScale(ColorScaleType:={scale.Colors.Count})");
                for (int i = 0; i < scale.Colors.Count; i++)
                {
                    Line(2, $"fc.ColorScaleCriteria({i + 1}).FormatColor.Color = {Rgb(scale.Colors[i])}");
                }
                break;
            case DataBarRule bar:
                Line(2, "Set fc = rng.FormatConditions.AddDatabar");
                Line(2, $"fc.BarColor.Color = {Rgb(bar.Color)}");
                break;
            case IconSetRule icons:
                string set = icons.Set switch
                {
                    IconSet.Arrows => "xl3Arrows",
                    IconSet.Flags => "xl3Flags",
                    IconSet.Traffic => "xl3TrafficLights1",
                    IconSet.Stars => "xl3Stars",
                    IconSet.Symbols => "xl3Symbols",
                    _ => "xl4CRV",
                };
                Line(2, "Set fc = rng.FormatConditions.AddIconSetCondition");
                Line(2, $"fc.IconSet = ActiveWorkbook.IconSets({set})");
                break;
            default:
                throw new InvalidOperationException();
        }
        // Rules take priority in the order they appear in the script.
        Line(2, "fc.SetLastPriority");
    }

    private void WriteCfAdd(Condition condition)
    {
        switch (condition)
        {
            case CompareCondition cmp:
            {
                string op = cmp.Op switch
                {
                    CompareOp.Equal => "xlEqual",
                    CompareOp.NotEqual => "xlNotEqual",
                    CompareOp.Less => "xlLess",
                    CompareOp.LessEqual => "xlLessEqual",
                    CompareOp.Greater => "xlGreater",
                    _ => "xlGreaterEqual",
                };
                Line(2, $"Set fc = rng.FormatConditions.Add(Type:=xlCellValue, Operator:={op}, Formula1:={CfOperand(cmp.Value)})");
                break;
            }
            case BetweenCondition between:
                Line(2, $"Set fc = rng.FormatConditions.Add(Type:=xlCellValue, Operator:={(between.Negate ? "xlNotBetween" : "xlBetween")}, " +
                        $"Formula1:={CfOperand(between.Low)}, Formula2:={CfOperand(between.High)})");
                break;
            case TextCondition text:
            {
                string op = text.Op switch
                {
                    TextOp.Contains => "xlContains",
                    TextOp.NotContains => "xlDoesNotContain",
                    TextOp.BeginsWith => "xlBeginsWith",
                    _ => "xlEndsWith",
                };
                Line(2, $"Set fc = rng.FormatConditions.Add(Type:=xlTextString, String:={Str(text.Text)}, TextOperator:={op})");
                break;
            }
            case CellStateCondition state:
                string type = state.State switch
                {
                    CellState.Blank => "xlBlanksCondition",
                    CellState.NonBlank => "xlNoBlanksCondition",
                    CellState.Error => "xlErrorsCondition",
                    _ => "xlNoErrorsCondition",
                };
                Line(2, $"Set fc = rng.FormatConditions.Add(Type:={type})");
                break;
            case RankCondition rank:
                Line(2, "Set fc = rng.FormatConditions.AddTop10");
                Line(2, $"fc.TopBottom = {(rank.Top ? "xlTop10Top" : "xlTop10Bottom")}");
                Line(2, $"fc.Rank = {rank.Rank}");
                Line(2, $"fc.Percent = {Bool(rank.Percent)}");
                break;
            case AverageCondition avg:
                Line(2, "Set fc = rng.FormatConditions.AddAboveAverage");
                Line(2, $"fc.AboveBelow = {(avg.Above ? "xlAboveAverage" : "xlBelowAverage")}");
                break;
            case DuplicateCondition dup:
                Line(2, "Set fc = rng.FormatConditions.AddUniqueValues");
                Line(2, $"fc.DupeUnique = {(dup.Duplicate ? "xlDuplicate" : "xlUnique")}");
                break;
            case DatePeriodCondition date:
                string period = date.Period switch
                {
                    DatePeriod.Today => "xlToday",
                    DatePeriod.Yesterday => "xlYesterday",
                    DatePeriod.Tomorrow => "xlTomorrow",
                    DatePeriod.Last7Days => "xlLast7Days",
                    DatePeriod.ThisWeek => "xlThisWeek",
                    DatePeriod.LastWeek => "xlLastWeek",
                    DatePeriod.NextWeek => "xlNextWeek",
                    DatePeriod.ThisMonth => "xlThisMonth",
                    DatePeriod.LastMonth => "xlLastMonth",
                    _ => "xlNextMonth",
                };
                Line(2, $"Set fc = rng.FormatConditions.Add(Type:=xlTimePeriod, DateOperator:={period})");
                break;
            case FormulaCondition formula:
                Line(2, $"Set fc = rng.FormatConditions.Add(Type:=xlExpression, Formula1:=XlwCfFormula({Str(formula.Formula)}, tl))");
                break;
            default:
                throw new InvalidOperationException();
        }
    }

    private static string CfOperand(Operand operand) => operand switch
    {
        NumberOperand n => Str("=" + Num(n.Value)),
        TextOperand t => Str("=\"" + t.Value.Replace("\"", "\"\"") + "\""),
        // VBA reads relative references in conditional formats from the active cell, so rebase them.
        CellOperand c => $"XlwCfFormula({Str("=" + c.Address)}, tl)",
        _ => throw new InvalidOperationException(),
    };

    private void WriteCfAction(FormatAction action)
    {
        switch (action)
        {
            case ToggleAction t:
                Line(2, t.Property switch
                {
                    ToggleProperty.Bold => $"fc.Font.Bold = {Bool(t.On)}",
                    ToggleProperty.Italic => $"fc.Font.Italic = {Bool(t.On)}",
                    ToggleProperty.Underline => $"fc.Font.Underline = {(t.On ? "xlUnderlineStyleSingle" : "xlUnderlineStyleNone")}",
                    ToggleProperty.Strike => $"fc.Font.Strikethrough = {Bool(t.On)}",
                    _ => throw new InvalidOperationException(),
                });
                break;
            case FillAction f: Line(2, $"fc.Interior.Color = {Rgb(f.Color)}"); break;
            case FontColorAction f: Line(2, $"fc.Font.Color = {Rgb(f.Color)}"); break;
            case NumberFormatAction n: Line(2, $"fc.NumberFormat = {Str(n.Format)}"); break;
            case BorderAction border:
                (string lineStyle, _) = BorderLine(border.Style);
                foreach ((BorderSides side, string index) in CfBorderIndexes)
                {
                    if ((border.Sides & side) == 0) continue;
                    Line(2, $"fc.Borders({index}).LineStyle = {lineStyle}");
                    if (border.Style != BorderStyle.None) Line(2, $"fc.Borders({index}).Color = {Rgb(border.Color)}");
                }
                break;
            default:
                throw new InvalidOperationException();
        }
    }

    private static readonly (BorderSides, string)[] CfBorderIndexes =
    {
        (BorderSides.Top, "xlTop"),
        (BorderSides.Bottom, "xlBottom"),
        (BorderSides.Left, "xlLeft"),
        (BorderSides.Right, "xlRight"),
    };

    // Literals

    private void Line(int indent, string text)
    {
        _b.Append(' ', indent * 4);
        _b.Append(text);
        _b.Append('\n');
    }

    public static string Str(string value)
    {
        string escaped = "\"" + value.Replace("\"", "\"\"") + "\"";
        // VBA string literals can't span lines.
        return escaped.Replace("\r\n", "\" & vbCrLf & \"").Replace("\n", "\" & vbLf & \"");
    }

    private static string Num(double value) => value.ToString("R", CultureInfo.InvariantCulture);

    private static string Bool(bool value) => value ? "True" : "False";

    private static string Rgb(Rgb c) => $"RGB({c.R}, {c.G}, {c.B})";

    private const string Helpers = """

' Union that tolerates Nothing on either side.
Private Function XlwUnion(a As Range, b As Range) As Range
    If a Is Nothing Then
        Set XlwUnion = b
    ElseIf b Is Nothing Then
        Set XlwUnion = a
    Else
        Set XlwUnion = Application.Union(a, b)
    End If
End Function

' Table starting at anchor: extends right until the first blank header cell,
' then down until a row that is blank across the full table width.
Private Function XlwTable(anchor As Range) As Range
    Dim ws As Worksheet, lastRow As Long, lastCol As Long
    Set ws = anchor.Worksheet
    Set anchor = anchor.Cells(1, 1)
    lastCol = anchor.Column
    Do While lastCol < ws.Columns.Count
        If IsEmpty(ws.Cells(anchor.Row, lastCol + 1).Value) Then Exit Do
        lastCol = lastCol + 1
    Loop
    lastRow = anchor.Row
    Do While lastRow < ws.Rows.Count
        If Application.WorksheetFunction.CountA(ws.Range(ws.Cells(lastRow + 1, anchor.Column), ws.Cells(lastRow + 1, lastCol))) = 0 Then Exit Do
        lastRow = lastRow + 1
    Loop
    Set XlwTable = ws.Range(anchor, ws.Cells(lastRow, lastCol))
End Function

Private Function XlwTablePart(t As Range, part As String) As Range
    Select Case part
        Case "header"
            Set XlwTablePart = t.Rows(1)
        Case "body"
            If t.Rows.Count > 1 Then Set XlwTablePart = t.Offset(1, 0).Resize(t.Rows.Count - 1)
        Case "lastrow"
            If t.Rows.Count > 1 Then Set XlwTablePart = t.Rows(t.Rows.Count)
    End Select
End Function

' Body cells of the column whose header matches headerText (case-insensitive).
Private Function XlwTableColumn(t As Range, headerText As String) As Range
    Dim i As Long
    For i = 1 To t.Columns.Count
        If StrComp(Trim(CStr(t.Cells(1, i).Text)), Trim(headerText), vbTextCompare) = 0 Then
            If t.Rows.Count > 1 Then Set XlwTableColumn = t.Cells(2, i).Resize(t.Rows.Count - 1, 1)
            Exit Function
        End If
    Next i
    Err.Raise vbObjectError + 1, "xlwrite", "No column with header '" & headerText & "' in table " & t.Address(False, False) & " on sheet '" & t.Worksheet.Name & "'."
End Function

' Collects kept cells, merging horizontal runs so large filters don't build one area per cell.
' Pass Nothing for c to flush the final run.
Private Sub XlwKeep(kept As Range, rs As Range, re As Range, c As Range)
    If Not re Is Nothing Then
        If Not c Is Nothing Then
            If c.Row = re.Row And c.Column = re.Column + 1 Then
                Set re = c
                Exit Sub
            End If
        End If
        Set kept = XlwUnion(kept, rs.Worksheet.Range(rs, re))
    End If
    Set rs = c
    Set re = c
End Sub

Private Function XlwIsNumber(v As Variant) As Boolean
    Select Case VarType(v)
        Case vbInteger, vbLong, vbSingle, vbDouble, vbCurrency, vbDate, vbDecimal
            XlwIsNumber = True
    End Select
End Function

' Blank cells and errors never match an ordering; numbers only compare with numbers
' and text only with text (case-insensitive). '<>' is the negation of '='.
Private Function XlwCompare(v As Variant, op As String, x As Variant) As Boolean
    Dim d As Integer
    If op = "<>" Then
        XlwCompare = Not XlwCompare(v, "=", x)
        Exit Function
    End If
    If IsError(v) Or IsError(x) Or IsEmpty(v) Then Exit Function
    If XlwIsNumber(v) And XlwIsNumber(x) Then
        d = Sgn(CDbl(v) - CDbl(x))
    ElseIf VarType(v) = vbString And VarType(x) = vbString Then
        d = StrComp(v, x, vbTextCompare)
    Else
        Exit Function
    End If
    Select Case op
        Case "=": XlwCompare = (d = 0)
        Case "<": XlwCompare = (d < 0)
        Case "<=": XlwCompare = (d <= 0)
        Case ">": XlwCompare = (d > 0)
        Case ">=": XlwCompare = (d >= 0)
    End Select
End Function

' Inclusive, and the bounds may be given in either order. Only comparable values match either way.
Private Function XlwBetween(v As Variant, lo As Variant, hi As Variant, negate As Boolean) As Boolean
    Dim inside As Boolean
    If Not (XlwCompare(v, "=", lo) Or XlwCompare(v, "<", lo) Or XlwCompare(v, ">", lo)) Then Exit Function
    inside = (XlwCompare(v, ">=", lo) And XlwCompare(v, "<=", hi)) Or (XlwCompare(v, ">=", hi) And XlwCompare(v, "<=", lo))
    XlwBetween = (inside <> negate)
End Function

Private Function XlwText(v As Variant, op As String, t As String) As Boolean
    Dim s As String
    If IsError(v) Then
        XlwText = (op = "notcontains")
        Exit Function
    End If
    s = CStr(v)
    Select Case op
        Case "contains": XlwText = InStr(1, s, t, vbTextCompare) > 0
        Case "notcontains": XlwText = InStr(1, s, t, vbTextCompare) = 0
        Case "begins": XlwText = StrComp(Left(s, Len(t)), t, vbTextCompare) = 0
        Case "ends": XlwText = StrComp(Right(s, Len(t)), t, vbTextCompare) = 0
    End Select
End Function

Private Function XlwBlank(v As Variant) As Boolean
    If IsError(v) Then Exit Function
    XlwBlank = Len(Trim(CStr(v))) = 0
End Function

' Numeric values in the range as an array, or Empty when there are none.
Private Function XlwNumbers(rng As Range) As Variant
    Dim vals() As Double, n As Long, area As Range, cell As Range
    For Each area In rng.Areas
        For Each cell In area.Cells
            If XlwIsNumber(cell.Value) Then
                ReDim Preserve vals(n)
                vals(n) = CDbl(cell.Value)
                n = n + 1
            End If
        Next cell
    Next area
    If n > 0 Then XlwNumbers = vals
End Function

' Value a cell must reach to be in the top (or bottom) n, or n percent, of the range.
Private Function XlwRankThreshold(rng As Range, top As Boolean, n As Long, pct As Boolean) As Variant
    Dim vals As Variant, cnt As Long, k As Long
    vals = XlwNumbers(rng)
    If IsEmpty(vals) Then Exit Function
    cnt = UBound(vals) + 1
    If pct Then k = Int(cnt * n / 100) Else k = n
    If k < 1 Then k = 1
    If k > cnt Then k = cnt
    If top Then
        XlwRankThreshold = Application.WorksheetFunction.Large(vals, k)
    Else
        XlwRankThreshold = Application.WorksheetFunction.Small(vals, k)
    End If
End Function

Private Function XlwAverage(rng As Range) As Variant
    Dim vals As Variant
    vals = XlwNumbers(rng)
    If Not IsEmpty(vals) Then XlwAverage = Application.WorksheetFunction.Average(vals)
End Function

Private Function XlwKey(v As Variant) As String
    If XlwIsNumber(v) Then XlwKey = "n" & CStr(CDbl(v)) Else XlwKey = "s" & LCase(CStr(v))
End Function

' Count of each non-blank value in the range. Collection keys are case-insensitive, like Excel.
Private Function XlwCounts(rng As Range) As Collection
    Dim counts As New Collection, area As Range, cell As Range, k As String, n As Long
    For Each area In rng.Areas
        For Each cell In area.Cells
            If Not IsError(cell.Value) And Not XlwBlank(cell.Value) Then
                k = XlwKey(cell.Value)
                n = 0
                On Error Resume Next
                n = counts(k)
                counts.Remove k
                On Error GoTo 0
                counts.Add n + 1, k
            End If
        Next cell
    Next area
    Set XlwCounts = counts
End Function

' True when v's count matches the wanted kind. Blank and error cells are neither duplicate nor unique.
Private Function XlwDupMatch(counts As Collection, v As Variant, duplicate As Boolean) As Boolean
    If IsError(v) Then Exit Function
    If XlwBlank(v) Then Exit Function
    XlwDupMatch = ((counts(XlwKey(v)) > 1) = duplicate)
End Function

' Weeks run Sunday to Saturday, matching Excel's conditional formatting.
Private Function XlwDatePeriod(v As Variant, period As String) As Boolean
    Dim d As Long, t As Long, wk As Long, m As Date
    If IsError(v) Or IsEmpty(v) Then Exit Function
    If Not XlwIsNumber(v) Then Exit Function
    d = Int(CDbl(v))
    t = CLng(Date)
    wk = t - Weekday(Date, vbSunday) + 1
    Select Case period
        Case "today": XlwDatePeriod = (d = t)
        Case "yesterday": XlwDatePeriod = (d = t - 1)
        Case "tomorrow": XlwDatePeriod = (d = t + 1)
        Case "last7days": XlwDatePeriod = (d >= t - 6 And d <= t)
        Case "thisweek": XlwDatePeriod = (d >= wk And d <= wk + 6)
        Case "lastweek": XlwDatePeriod = (d >= wk - 7 And d <= wk - 1)
        Case "nextweek": XlwDatePeriod = (d >= wk + 7 And d <= wk + 13)
        Case "thismonth", "lastmonth", "nextmonth"
            m = DateSerial(Year(Date), Month(Date) + IIf(period = "lastmonth", -1, IIf(period = "nextmonth", 1, 0)), 1)
            XlwDatePeriod = (Year(CDate(d)) = Year(m) And Month(CDate(d)) = Month(m))
    End Select
End Function

' Formula relative to 'origin' converted to R1C1, so it can be re-anchored at any cell.
Private Function XlwToR1C1(f As String, origin As Range) As String
    XlwToR1C1 = Application.ConvertFormula(f, xlA1, xlR1C1, , origin)
End Function

Private Function XlwEvalAt(r1c1 As String, c As Range) As Variant
    XlwEvalAt = c.Worksheet.Evaluate(Application.ConvertFormula(r1c1, xlR1C1, xlA1, , c))
End Function

Private Function XlwTruthy(v As Variant) As Boolean
    If IsError(v) Then Exit Function
    If VarType(v) = vbBoolean Then
        XlwTruthy = v
    ElseIf XlwIsNumber(v) Then
        XlwTruthy = (CDbl(v) <> 0)
    End If
End Function

' Conditional format formulas added from VBA are read relative to the active cell,
' so rebase a formula written relative to 'origin' onto it.
Private Function XlwCfFormula(f As String, origin As Range) As String
    XlwCfFormula = Application.ConvertFormula(XlwToR1C1(f, origin), xlR1C1, xlA1, , ActiveCell)
End Function

' Borders on each area, skipping inside borders an area doesn't have.
Private Sub XlwBorder(rng As Range, index As Long, lineStyle As Long, weight As Long, color As Long)
    Dim area As Range
    For Each area In rng.Areas
        If index = xlInsideHorizontal And area.Rows.Count = 1 Then GoTo NextArea
        If index = xlInsideVertical And area.Columns.Count = 1 Then GoTo NextArea
        With area.Borders(index)
            .LineStyle = lineStyle
            If lineStyle <> xlLineStyleNone Then
                .Weight = weight
                .Color = color
            End If
        End With
NextArea:
    Next area
End Sub
""";
}
