//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XlWrite.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="XlWriteParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IXlWriteListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] XlWriteParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] XlWriteParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterItem([NotNull] XlWriteParser.ItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitItem([NotNull] XlWriteParser.ItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRange([NotNull] XlWriteParser.RangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRange([NotNull] XlWriteParser.RangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection([NotNull] XlWriteParser.SelectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection([NotNull] XlWriteParser.SelectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.actions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterActions([NotNull] XlWriteParser.ActionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.actions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitActions([NotNull] XlWriteParser.ActionsContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>fillActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFillActionExp([NotNull] XlWriteParser.FillActionExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>fillActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFillActionExp([NotNull] XlWriteParser.FillActionExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>widthActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWidthActionExp([NotNull] XlWriteParser.WidthActionExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>widthActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWidthActionExp([NotNull] XlWriteParser.WidthActionExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>borderActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBorderActionExp([NotNull] XlWriteParser.BorderActionExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>borderActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBorderActionExp([NotNull] XlWriteParser.BorderActionExpContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>boldActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoldActionExp([NotNull] XlWriteParser.BoldActionExpContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>boldActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoldActionExp([NotNull] XlWriteParser.BoldActionExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.boldAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoldAction([NotNull] XlWriteParser.BoldActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.boldAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoldAction([NotNull] XlWriteParser.BoldActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.fillAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFillAction([NotNull] XlWriteParser.FillActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.fillAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFillAction([NotNull] XlWriteParser.FillActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.widthAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWidthAction([NotNull] XlWriteParser.WidthActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.widthAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWidthAction([NotNull] XlWriteParser.WidthActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.borderAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBorderAction([NotNull] XlWriteParser.BorderActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.borderAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBorderAction([NotNull] XlWriteParser.BorderActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColor([NotNull] XlWriteParser.ColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColor([NotNull] XlWriteParser.ColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.knownColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterKnownColor([NotNull] XlWriteParser.KnownColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.knownColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitKnownColor([NotNull] XlWriteParser.KnownColorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.rgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRgbColor([NotNull] XlWriteParser.RgbColorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.rgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRgbColor([NotNull] XlWriteParser.RgbColorContext context);
}
