//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XlWrite.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IXlWriteListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class XlWriteBaseListener : IXlWriteListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFile([NotNull] XlWriteParser.FileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.file"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFile([NotNull] XlWriteParser.FileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterItem([NotNull] XlWriteParser.ItemContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.item"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitItem([NotNull] XlWriteParser.ItemContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRange([NotNull] XlWriteParser.RangeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.range"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRange([NotNull] XlWriteParser.RangeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection([NotNull] XlWriteParser.SelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection([NotNull] XlWriteParser.SelectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.actions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterActions([NotNull] XlWriteParser.ActionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.actions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitActions([NotNull] XlWriteParser.ActionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>fillActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFillActionExp([NotNull] XlWriteParser.FillActionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>fillActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFillActionExp([NotNull] XlWriteParser.FillActionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>widthActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWidthActionExp([NotNull] XlWriteParser.WidthActionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>widthActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWidthActionExp([NotNull] XlWriteParser.WidthActionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>borderActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBorderActionExp([NotNull] XlWriteParser.BorderActionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>borderActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBorderActionExp([NotNull] XlWriteParser.BorderActionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>boldActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoldActionExp([NotNull] XlWriteParser.BoldActionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>boldActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoldActionExp([NotNull] XlWriteParser.BoldActionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.boldAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoldAction([NotNull] XlWriteParser.BoldActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.boldAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoldAction([NotNull] XlWriteParser.BoldActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.fillAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFillAction([NotNull] XlWriteParser.FillActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.fillAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFillAction([NotNull] XlWriteParser.FillActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.widthAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWidthAction([NotNull] XlWriteParser.WidthActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.widthAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWidthAction([NotNull] XlWriteParser.WidthActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.borderAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBorderAction([NotNull] XlWriteParser.BorderActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.borderAction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBorderAction([NotNull] XlWriteParser.BorderActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColor([NotNull] XlWriteParser.ColorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.color"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColor([NotNull] XlWriteParser.ColorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.knownColor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterKnownColor([NotNull] XlWriteParser.KnownColorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.knownColor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitKnownColor([NotNull] XlWriteParser.KnownColorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="XlWriteParser.rgbColor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRgbColor([NotNull] XlWriteParser.RgbColorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="XlWriteParser.rgbColor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRgbColor([NotNull] XlWriteParser.RgbColorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
