//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from XlWrite.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="XlWriteParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IXlWriteVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] XlWriteParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.item"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitItem([NotNull] XlWriteParser.ItemContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.range"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRange([NotNull] XlWriteParser.RangeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection([NotNull] XlWriteParser.SelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.actions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitActions([NotNull] XlWriteParser.ActionsContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>fillActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFillActionExp([NotNull] XlWriteParser.FillActionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>widthActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthActionExp([NotNull] XlWriteParser.WidthActionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>borderActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBorderActionExp([NotNull] XlWriteParser.BorderActionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>boldActionExp</c>
	/// labeled alternative in <see cref="XlWriteParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoldActionExp([NotNull] XlWriteParser.BoldActionExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.boldAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoldAction([NotNull] XlWriteParser.BoldActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.fillAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFillAction([NotNull] XlWriteParser.FillActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.widthAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWidthAction([NotNull] XlWriteParser.WidthActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.borderAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBorderAction([NotNull] XlWriteParser.BorderActionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.color"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColor([NotNull] XlWriteParser.ColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.knownColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitKnownColor([NotNull] XlWriteParser.KnownColorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="XlWriteParser.rgbColor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRgbColor([NotNull] XlWriteParser.RgbColorContext context);
}
