name: Build and Test

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9
    - name: Build
      run: dotnet build
    - name: Test NUnit
      run: dotnet test
